obj-y += at_parser.o at_parser_send.o at_parser_receive.o 
obj-$(CONFIG_AT_PARSER_TEST) += at_parser_test.o at_parser_cmd_basic.o
obj-$(CONFIG_AT_PARSER_ENABLE_ZEPHYR_HAL) += zephyr_hal/
obj-$(CONFIG_AT_PARSER_ENABLE_FREERTOS_HAL) += freertos_hal/
