echo "clean up other useless directory"
#rm -rf ./arch/mips/soc/actions/woodpeckerfpga
rm -rf ./doc/
rm -rf ./drivers/ethernet/
rm -rf ./drivers/ieee802154/
rm -rf ./drivers/pci/
rm -rf ./drivers/sensor/
rm -rf ./drivers/wifi/
rm -rf ./drivers/sensor/adxl362/
rm -rf ./drivers/sensor/ak8975/
rm -rf ./drivers/sensor/apds9960/
rm -rf ./drivers/sensor/bma280/
rm -rf ./drivers/sensor/bmc150_magn/
rm -rf ./drivers/sensor/bme280/
rm -rf ./drivers/sensor/bmg160/
rm -rf ./drivers/sensor/bmi160/
rm -rf ./drivers/sensor/bmm150/
rm -rf ./drivers/sensor/dht/
rm -rf ./drivers/sensor/fxas21002/
rm -rf ./drivers/sensor/fxos8700/
rm -rf ./drivers/sensor/hdc1008/
rm -rf ./drivers/sensor/hmc5883l/
rm -rf ./drivers/sensor/hp206c/
rm -rf ./drivers/sensor/hts221/
rm -rf ./drivers/sensor/isl29035/
rm -rf ./drivers/sensor/lis2dh/
rm -rf ./drivers/sensor/lis3dh/
rm -rf ./drivers/sensor/lis3mdl/
rm -rf ./drivers/sensor/lps22hb/
rm -rf ./drivers/sensor/lps25hb/
rm -rf ./drivers/sensor/lsm6ds0/
rm -rf ./drivers/sensor/lsm6dsl/
rm -rf ./drivers/sensor/lsm9ds0_gyro/
rm -rf ./drivers/sensor/lsm9ds0_mfd/
rm -rf ./drivers/sensor/max30101/
rm -rf ./drivers/sensor/max44009/
rm -rf ./drivers/sensor/mcp9808/
rm -rf ./drivers/sensor/mpu6050/
rm -rf ./drivers/sensor/nrf5/
rm -rf ./drivers/sensor/sht3xd/
rm -rf ./drivers/sensor/sx9500/
rm -rf ./drivers/sensor/th02/
rm -rf ./drivers/sensor/tmp007/
rm -rf ./drivers/sensor/tmp112/
rm -rf ./drivers/pinmux/beetle/
rm -rf ./drivers/pinmux/dev
rm -rf ./drivers/pinmux/pinmux_cc2650.c
rm -rf ./drivers/pinmux/pinmux_esp32.c
rm -rf ./drivers/pinmux/pinmux_fe310.c
rm -rf ./drivers/pinmux/pinmux_mcux.c
rm -rf ./drivers/pinmux/pinmux_qmsi.c
rm -rf ./drivers/pinmux/stm32/
rm -rf ./drivers/interrupt_controller/arcv2_irq_unit.c
rm -rf ./drivers/interrupt_controller/exti_stm32.c
rm -rf ./drivers/interrupt_controller/exti_stm32.h
rm -rf ./drivers/interrupt_controller/i8259.c
rm -rf ./drivers/interrupt_controller/ioapic_intr.c
rm -rf ./drivers/interrupt_controller/ioapic_priv.h
rm -rf ./drivers/interrupt_controller/loapic_intr.c
rm -rf ./drivers/interrupt_controller/loapic_spurious.S
rm -rf ./drivers/interrupt_controller/mvic.c
rm -rf ./drivers/interrupt_controller/plic_fe310.c
rm -rf ./drivers/interrupt_controller/system_apic.c
rm -rf ./drivers/interrupt_controller/Kconfig.stm32
#rm -rf ./drivers/interrupt_controller/
rm -rf ./drivers/ipm/
rm -rf ./drivers/i2c/i2c_ll_stm32.c
rm -rf ./drivers/i2c/i2c_ll_stm32.h
rm -rf ./drivers/i2c/i2c_ll_stm32_v1.c
rm -rf ./drivers/i2c/i2c_ll_stm32_v2.c
rm -rf ./drivers/i2c/i2c_mcux.c
rm -rf ./drivers/i2c/i2c_nrf5.c
rm -rf ./drivers/i2c/i2c-priv.h
rm -rf ./drivers/i2c/i2c_qmsi.c
rm -rf ./drivers/i2c/i2c_qmsi_ss.c
rm -rf ./drivers/i2c/i2c_sbcon.c
rm -rf ./drivers/grove/lcd_rgb.c
rm -rf ./drivers/grove/light_sensor.c
rm -rf ./drivers/grove/temperature_sensor.c
rm -rf ./drivers/grove/
rm -rf ./drivers/flash/flash_stm32.c
rm -rf ./drivers/flash/flash_stm32f3x.c
rm -rf ./drivers/flash/flash_stm32f3x.h
rm -rf ./drivers/flash/flash_stm32f3x_priv.c
rm -rf ./drivers/flash/flash_stm32f4x.c
rm -rf ./drivers/flash/flash_stm32.h
rm -rf ./drivers/flash/flash_stm32l4x.c
rm -rf ./drivers/crypto/crypto_ataes132a.c
rm -rf ./drivers/crypto/crypto_ataes132a_priv.h
rm -rf ./drivers/crypto/crypto_mtls_shim.c
rm -rf ./drivers/crypto/crypto_tc_shim.c
rm -rf ./drivers/crypto/crypto_tc_shim_priv.h
rm -rf ./drivers/crypto/Kconfig.ataes132a
rm -rf ./drivers/crypto/
rm -rf ./drivers/counter/counter_dtmr_cmsdk_apb.c
rm -rf ./drivers/counter/counter_qmsi_aon.c
rm -rf ./drivers/counter/counter_qmsi_aonpt.c
rm -rf ./drivers/counter/counter_tmr_cmsdk_apb.c
rm -rf ./drivers/counter/dualtimer_cmsdk_apb.h
rm -rf ./drivers/counter/timer_cmsdk_apb.h
rm -rf ./drivers/counter/timer_dtmr_cmsdk_apb.c
rm -rf ./drivers/counter/timer_tmr_cmsdk_apb.c
rm -rf ./drivers/counter/Kconfig.dtmr_cmsdk_apb
rm -rf ./drivers/counter/Kconfig.qmsi
rm -rf ./drivers/counter/Kconfig.tmr_cmsdk_apb
rm -rf ./drivers/counter/
rm -rf ./drivers/clock_control/beetle_clock_control.c
rm -rf ./drivers/clock_control/nrf5_power_clock.c
rm -rf ./drivers/clock_control/quark_se_clock_control.c
rm -rf ./drivers/clock_control/stm32f1x_ll_clock.c
rm -rf ./drivers/clock_control/stm32f3x_ll_clock.c
rm -rf ./drivers/clock_control/stm32f4x_ll_clock.c
rm -rf ./drivers/clock_control/stm32l4x_ll_clock.c
rm -rf ./drivers/clock_control/stm32_ll_clock.c
rm -rf ./drivers/clock_control/stm32_ll_clock.h
rm -rf ./drivers/clock_control/Kconfig.beetle
rm -rf ./drivers/clock_control/Kconfig.nrf5
rm -rf ./drivers/clock_control/Kconfig.quark_se
rm -rf ./drivers/clock_control/Kconfig.stm32
rm -rf ./drivers/clock_control/
rm -rf ./drivers/aio/
rm -rf ./drivers/adc/adc_dw.c
rm -rf ./drivers/adc/adc_dw.h
rm -rf ./drivers/adc/adc_mcux_adc16.c
rm -rf ./drivers/adc/adc_qmsi.c
rm -rf ./drivers/adc/adc_qmsi_ss.c
rm -rf ./drivers/adc/adc_ti_adc108s102.c
rm -rf ./drivers/adc/adc_ti_adc108s102.h
rm -rf ./drivers/watchdog/iwdg_stm32.c
rm -rf ./drivers/watchdog/iwdg_stm32.h
rm -rf ./drivers/watchdog/Kconfig.cmsdk_apb
rm -rf ./drivers/watchdog/Kconfig.esp32
rm -rf ./drivers/watchdog/Kconfig.qmsi
rm -rf ./drivers/watchdog/Kconfig.sam
rm -rf ./drivers/watchdog/Kconfig.stm32
rm -rf ./drivers/watchdog/wdog_cmsdk_apb.c
rm -rf ./drivers/watchdog/wdt_esp32.c
rm -rf ./drivers/watchdog/wdt_qmsi.c
rm -rf ./drivers/watchdog/wdt_sam.c
rm -rf ./drivers/spi/Kconfig.dw
rm -rf ./drivers/spi/Kconfig.mcux_dspi
rm -rf ./drivers/spi/Kconfig.nrf5_legacy
rm -rf ./drivers/spi/spi_dw.c
rm -rf ./drivers/spi/spi_dw.h
rm -rf ./drivers/spi/spi_dw_legacy.c
rm -rf ./drivers/spi/spi_dw_quark_se_ss_regs.h
rm -rf ./drivers/spi/spi_dw_regs.h
rm -rf ./drivers/spi/spi_intel.c
rm -rf ./drivers/spi/spi_intel.h
rm -rf ./drivers/spi/spi_ll_stm32.c
rm -rf ./drivers/spi/spi_ll_stm32.h
rm -rf ./drivers/spi/spi_mcux_dspi.c
rm -rf ./drivers/spi/spi_qmsi.c
rm -rf ./drivers/spi/spi_qmsi_ss.c
rm -rf ./drivers/spi/spim_nrf52_legacy.c
rm -rf ./drivers/spi/spis_nrf5_legacy.c
rm -rf ./drivers/serial/Kconfig.altera_jtag
rm -rf ./drivers/serial/Kconfig.atmel_sam3
rm -rf ./drivers/serial/Kconfig.cc32xx
rm -rf ./drivers/serial/Kconfig.cmsdk_apb
rm -rf ./drivers/serial/Kconfig.esp32
rm -rf ./drivers/serial/Kconfig.fe310
rm -rf ./drivers/serial/Kconfig.mcux
rm -rf ./drivers/serial/Kconfig.mcux_lpsci
rm -rf ./drivers/serial/Kconfig.mcux_lpuart
rm -rf ./drivers/serial/Kconfig.nrf5
rm -rf ./drivers/serial/Kconfig.ns16550
rm -rf ./drivers/serial/Kconfig.nsim
rm -rf ./drivers/serial/Kconfig.qmsi
rm -rf ./drivers/serial/Kconfig.riscv_qemu
rm -rf ./drivers/serial/Kconfig.stellaris
rm -rf ./drivers/serial/Kconfig.stm32
rm -rf ./drivers/serial/Kconfig.uart_sam
rm -rf ./drivers/serial/Kconfig.usart_sam
rm -rf ./drivers/serial/uart_altera_jtag.c
rm -rf ./drivers/serial/uart_atmel_sam3.c
rm -rf ./drivers/serial/uart_cc32xx.c
rm -rf ./drivers/serial/uart_cmsdk_apb.c
rm -rf ./drivers/serial/uart_esp32.c
rm -rf ./drivers/serial/uart_fe310.c
rm -rf ./drivers/serial/uart_mcux.c
rm -rf ./drivers/serial/uart_mcux_lpsci.c
rm -rf ./drivers/serial/uart_mcux_lpuart.c
rm -rf ./drivers/serial/uart_nrf5.c
rm -rf ./drivers/serial/uart_ns16550.c
rm -rf ./drivers/serial/uart_ns16550.h
rm -rf ./drivers/serial/uart_nsim.c
rm -rf ./drivers/serial/uart_qmsi.c
rm -rf ./drivers/serial/uart_riscv_qemu.c
rm -rf ./drivers/serial/uart_sam.c
rm -rf ./drivers/serial/uart_stellaris.c
rm -rf ./drivers/serial/uart_stm32.c
rm -rf ./drivers/serial/uart_stm32.h
rm -rf ./drivers/serial/usart_sam.c
rm -rf ./drivers/serial/uart_acts_stub.c
rm -rf ./drivers/rtc/rtc_pcf8563.c
rm -rf ./drivers/rtc/rtc_qmsi.c
rm -rf ./drivers/random/Kconfig.esp32
rm -rf ./drivers/random/Kconfig.mcux
rm -rf ./drivers/random/Kconfig.stm32
rm -rf ./drivers/random/random_esp32.c
rm -rf ./drivers/random/random_mcux_rnga.c
rm -rf ./drivers/random/random_mcux_trng.c
rm -rf ./drivers/random/random_stm32_rng.c
rm -rf ./drivers/pwm/Kconfig.dw
rm -rf ./drivers/pwm/Kconfig.mcux_ftm
rm -rf ./drivers/pwm/Kconfig.nrf5_sw
rm -rf ./drivers/pwm/Kconfig.pca9685
rm -rf ./drivers/pwm/Kconfig.qmsi
rm -rf ./drivers/pwm/Kconfig.stm32
rm -rf ./drivers/pwm/pwm_dw.c
rm -rf ./drivers/pwm/pwm_mcux_ftm.c
rm -rf ./drivers/pwm/pwm_nrf5_sw.c
rm -rf ./drivers/pwm/pwm_pca9685.c
rm -rf ./drivers/pwm/pwm_pca9685.h
rm -rf ./drivers/pwm/pwm_qmsi.c
rm -rf ./drivers/pwm/pwm_stm32.c
rm -rf ./drivers/pwm/pwm_stm32.h
rm -rf ./drivers/pinmux/Kconfig.beetle
rm -rf ./drivers/pinmux/Kconfig.cc2650
rm -rf ./drivers/pinmux/Kconfig.esp32
rm -rf ./drivers/pinmux/Kconfig.fe310
rm -rf ./drivers/pinmux/Kconfig.mcux
rm -rf ./drivers/pinmux/Kconfig.stm32
rm -rf ./drivers/pinmux/pinmux_quark_mcu.h
rm -rf ./drivers/i2c/i2c_atmel_sam3.c
rm -rf ./drivers/i2c/i2c_dw.c
rm -rf ./drivers/i2c/i2c_dw.h
rm -rf ./drivers/i2c/i2c_dw_registers.h
rm -rf ./drivers/i2c/Kconfig.sbcon
rm -rf ./drivers/i2c/twihs_sam.c
rm -rf ./drivers/i2c/i2c_bitbang.c
rm -rf ./drivers/i2c/i2c_bitbang.h
rm -rf ./drivers/gpio/gpio_atmel_sam3.c
rm -rf ./drivers/gpio/gpio_cc2650.c
rm -rf ./drivers/gpio/gpio_cc32xx.c
rm -rf ./drivers/gpio/gpio_cmsdk_ahb.c
rm -rf ./drivers/gpio/gpio_cmsdk_ahb.h
rm -rf ./drivers/gpio/gpio_dw.c
rm -rf ./drivers/gpio/gpio_dw.h
rm -rf ./drivers/gpio/gpio_dw_registers.h
rm -rf ./drivers/gpio/gpio_esp32.c
rm -rf ./drivers/gpio/gpio_fe310.c
rm -rf ./drivers/gpio/gpio_mcux.c
rm -rf ./drivers/gpio/gpio_mmio32.c
rm -rf ./drivers/gpio/gpio_nrf5.c
rm -rf ./drivers/gpio/gpio_pcal9535a.c
rm -rf ./drivers/gpio/gpio_pcal9535a.h
rm -rf ./drivers/gpio/gpio_pulpino.c
rm -rf ./drivers/gpio/gpio_qmsi.c
rm -rf ./drivers/gpio/gpio_qmsi_ss.c
rm -rf ./drivers/gpio/gpio_sch.c
rm -rf ./drivers/gpio/gpio_sch.h
rm -rf ./drivers/gpio/gpio_stm32.c
rm -rf ./drivers/gpio/gpio_stm32.h
rm -rf ./drivers/gpio/Kconfig.atmel_sam3
rm -rf ./drivers/gpio/Kconfig.cc2650
rm -rf ./drivers/gpio/Kconfig.cc32xx
rm -rf ./drivers/gpio/Kconfig.cmsdk_ahb
rm -rf ./drivers/gpio/Kconfig.dw
rm -rf ./drivers/gpio/Kconfig.esp32
rm -rf ./drivers/gpio/Kconfig.fe310
rm -rf ./drivers/gpio/Kconfig.mcux
rm -rf ./drivers/gpio/Kconfig.mmio32
rm -rf ./drivers/gpio/Kconfig.nrf5
rm -rf ./drivers/gpio/Kconfig.pcal9535a
rm -rf ./drivers/gpio/Kconfig.pulpino
rm -rf ./drivers/gpio/Kconfig.qmsi
rm -rf ./drivers/gpio/Kconfig.sch
rm -rf ./drivers/gpio/Kconfig.stm32
rm -rf ./drivers/flash/Kconfig.stm32
rm -rf ./drivers/flash/soc_flash_mcux.c
rm -rf ./drivers/flash/soc_flash_nrf5.c
rm -rf ./drivers/flash/soc_flash_qmsi.c
rm -rf ./drivers/dma/dma_qmsi.c
rm -rf ./drivers/dma/dma_stm32f4x.c
rm -rf ./drivers/dma/Kconfig.qmsi
rm -rf ./drivers/dma/Kconfig.stm32f4x
rm -rf ./drivers/console/ipm_console_receiver.c
rm -rf ./drivers/console/ipm_console_sender.c
rm -rf ./drivers/console/Kconfig.telnet
rm -rf ./drivers/console/ram_console.c
rm -rf ./drivers/console/rtt_console.c
rm -rf ./drivers/console/telnet_console.c
rm -rf ./drivers/console/telnet_protocol.h
rm -rf ./drivers/console/xtensa_sim_console.c
rm -rf ./drivers/console/uart_pipe.c
rm -rf ./drivers/timer/altera_avalon_timer.c
rm -rf ./drivers/timer/arcv2_timer0.c
rm -rf ./drivers/timer/cortex_m_systick.c
rm -rf ./drivers/timer/hpet.c
rm -rf ./drivers/timer/loapic_timer.c
rm -rf ./drivers/timer/nrf_rtc_timer.c
rm -rf ./drivers/timer/pulpino_timer.c
rm -rf ./drivers/timer/riscv_machine_timer.c
rm -rf ./drivers/timer/xtensa_sys_timer.c
rm -rf ./dts/arm/
rm -rf ./dts/common/
rm -rf ./dts/x86/
#rm -rf ./samples/audio_demo/
#rm -rf ./samples/gatt_pts/
#rm -rf ./samples/hello_world/
#rm -rf ./samples/usb_audio_dongle_hog/
#rm -rf ./samples/usb_audio_sourcesink/
#rm -rf ./samples/usb_cdc_acm/
#rm -rf ./samples/usb_device/
#rm -rf ./scripts/support/actions/prebuilt/woodpeckerfpga
rm -rf ./subsys/btstack/
#rm -rf ./subsys/console/
rm -rf ./subsys/cpp/
rm -rf ./subsys/net/
rm -rf ./tests/actions_test/
rm -rf ./tests/benchmarks/
rm -rf ./tests/bluetooth/
rm -rf ./tests/booting/
rm -rf ./tests/compliance/
rm -rf ./tests/crypto/
rm -rf ./tests/drivers/
rm -rf ./tests/include/
rm -rf ./tests/kernel/
rm -rf ./tests/lib/
rm -rf ./tests/net/
rm -rf ./tests/power/
rm -rf ./tests/shell/
rm -rf ./tests/subsys/
rm -rf ./tests/unit/
rm -rf ./tests/ztest/
#rm -rf ./boards/mips/ats285xfpga_fpgab/
#rm -rf ./boards/mips/ats2853_dvb_512k/
#rm -rf ./boards/mips/ats2853_evb/
#rm -rf ./boards/mips/ats2853c_dvb/
#rm -rf ./boards/mips/ats2853t_dvb/
