subdir-ccflags-y += -USYS_LOG_DOMAIN -DSYS_LOG_DOMAIN=\"iterator\" -DSYS_LOG_NO_NEWLINE

obj-y += iterator.o
obj-$(CONFIG_BACKGROUND_ITERATOR) += scan_plist_iterator.o
obj-$(CONFIG_PLIST_ITERATOR) += file_plist_iterator.o
obj-$(CONFIG_DYN_PLIST_ITERATOR) += dyn_plist_iterator.o


